### ISSUE TITLE
Missing compileOnly dependencies

### ISSUE THREAD

**Issue by passsy** [StefMa/AndroidArtifacts#19]
I have dependencies added with `compileOnly` which should result in a dependency node in pom with `scope = provided`.
The dependency is missing at all.

**Comment by StefMa** [comment]
Delivered in #26

**Comment by StefMa** [comment]
Will be rolled back in #32 .
Reason is simple.
Why should an project-dependency download another dependency if the "another dependency" require the project-dependency to add it on compile time?! 😉
