### ISSUE TITLE
Missing sources

### ISSUE THREAD

**Issue by passsy** [StefMa/AndroidArtifacts#20]
The sources of this lib aren't published to bintray.

```
Could not find androidartifacts-sources.jar (guru.stefma.androidartifacts:androidartifacts:1.0.0).
Searched in the following locations:
    https://jcenter.bintray.com/guru/stefma/androidartifacts/androidartifacts/1.0.0/androidartifacts-1.0.0-sources.jar
```

It would be very helpful when I could see the source in my IDE to debug bugs

That's what I currently see:
![zd6sariydc](https://user-images.githubusercontent.com/1096485/42528347-75a7be94-847b-11e8-9816-b8e08c305083.png)

**Comment by StefMa** [comment]
The first version of the plugin was released manually.
That means I have only uploaded the compiled `jar` file.

Thanks to #24 (#15) the next release will include the sources and the javadoc
