### ISSUE TITLE
Wrong POM if `filetree` dependency is used

### ISSUE THREAD

**Issue by StefMa** [StefMa/AndroidArtifacts#39]
See https://github.com/StefMa/bintray-release/issues/4

Check how the **java** POM looks like if we have dependency with a `filetree` and change the Android POM accordingly.

**Comment by StefMa** [comment]
We failed already the second time because of this (see https://github.com/StefMa/bintray-release/issues/8).

But as I [commend there](https://github.com/StefMa/bintray-release/issues/8#issuecomment-424602501) maybe we should fail earlier - when we detect a **undefinied** dependency.
🤔

**Comment by prasannajeet** [comment]
Just to leave my 2 cents here @StefMa , I think failing during bintrayUpload/publishdebugMavenLocal gradle tasks might be the appropriate approach here. You may leave a error message like "Cannot create POM file, empty file dependencies, please remove implementation fileTree(include: ['*.jar'], dir: 'libs') from your build.gradle file"

Just a thought :)
