### ISSUE TITLE
variant.getJavaCompiler is deprecated in AS 3.3

### ISSUE THREAD

**Issue by qtiuto** [StefMa/AndroidArtifacts#87]
I can't build it nicely without defining  -Pandroid.debug.obsoleteApi=true

**Comment by StefMa** [comment]
What do you mean with nicely?
You can build but have a warning which is enjoying?
Or you can't even build?

**Comment by qtiuto** [comment]
I can't build without defining the argument in the command line arguments,
but defining the argument will generate a long stacktrace. Both are not
nice.

Stefan M. <notifications@github.com> 于 2019年1月18日周五 01:52写道：

> What do you mean with nicely?
> You can build but have a warning which is enjoying?
> Or you can't even build?
>
